from pydantic import BaseModel, Field
from app.core.config import llm
from app.agents.state import AgentState

# --- 1. FORCE STRICT JSON OUTPUT ---
# We want the Strategist to output a clean, focused block of text.
class StrategistOutput(BaseModel):
    gap_analysis: str = Field(description="A detailed analysis of what the competitors missed and the unique angle we will take.")


# --- 2. THE SYSTEM PROMPT ---
strategist_prompt = """You are an elite SEO Content Strategist for the travel blog 'Mysterioustrip'.
Your job is to find the 'Content Gap'. I will give you a travel topic and a summary of what the top 10 competitors are currently writing about.

Topic: {topic}
Competitor Landscape: {competitor_data}

Analyze the competitor landscape. What are they missing? Are they ignoring hidden costs, local transport tips, off-beat locations near the main attraction, or realistic itineraries? 
Write a 2-3 paragraph strategy detailing our unique angle and exactly what we must include in our article to outrank them and provide more value.
"""


# --- 3. THE MAIN NODE FUNCTION ---
def run_strategist(state: AgentState):
    print("--- 🧠 STRATEGIST AGENT: ANALYZING CONTENT GAPS ---")
    
    # Bind the LLM to our Pydantic model to ensure we get the exact format we need
    structured_llm = llm.with_structured_output(StrategistOutput)
    
    # Format the prompt using the state data generated by the Analyst in Phase 2
    formatted_prompt = strategist_prompt.format(
        topic=state["topic"],
        competitor_data=state["competitor_content"]
    )
    
    # Run the LLM to generate the gap analysis
    response = structured_llm.invoke(formatted_prompt)
    
    # Update the state with the new strategy, matching the key in state.py
    return {"strategist_gaps": response.gap_analysis}